# Change these first
owner: Trigone-Tech # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Corporate
    url: https://corporate.ayruu.com
  - name: Office
    url: https://office.ayruu.com
  - name: MyA
    url: $MS_CHATBOT_ENDPOINT
  - name: Contract
    url: $MS_CONTRACT_ENDPOINT
  - name: Organization
    url: $MS_ORGANIZATION_ENDPOINT
  - name: Engine
    url: $MS_ENGINE_ENDPOINT
  - name: Booker1
    url: $MS_CAR_ENDPOINT
  - name: Booker2
    url: $MS_DRIVER_ENDPOINT
  - name: Booker3
    url: $MS_FLIGHT_ENDPOINT
  - name: Booker4
    url: $MS_HOTEL_ENDPOINT
  - name: Booker5
    url: $MS_TRAIN_ENDPOINT
  - name: Feed
    url: $MS_FEED_ENDPOINT
  - name: Policy
    url: $MS_POLICY_ENDPOINT

assignees:
  - adaniloff
  - fvhde
  - samuel-chane

status-website:
  cname: live.ayruu.com
  logoUrl: https://corporate.ayruu.com/icons/favicon-128x128.png
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Ayruu status page"
  introTitle: "Ayruu's uptime monitor and status page"
  introMessage: "Retrieve our services' state (live) on this page, our planned maintenance and reports."
  
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
